name: hmgle's blog
markdown: redcarpet
highlighter: pygments
url: http://hmgle.github.io
baseurl: "" # the subpath of your site, e.g. /blog/

# comments
disqus:
  config: true
duoshuo:
  config: false
