name: hmgle's blog
markdown: kramdown
highlighter: rouge
url: https://hmgle.github.io
baseurl: "" # the subpath of your site, e.g. /blog/

gems:
  - jekyll-gist

# comments
disqus:
  config: true
duoshuo:
  config: false
