name: hmgle's blog
markdown: kramdown
highlighter: rouge
url: https://hmgle.github.io
baseurl: "" # the subpath of your site, e.g. /blog/

plugins:
  - jekyll-gist
  - jekyll-feed

# comments
disqus:
  config: true
duoshuo:
  config: false
